[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"

[target.aarch64-pc-windows-gnu]
linker = "aarch64-w64-mingw32-gcc"

[target.armv7-pc-windows-gnu]
linker = "armv7-w64-mingw32-gcc"
